### ISSUE TITLE
Tweet entry?

### ISSUE THREAD

**Issue by jamesmontemagno** [paulpatarinski/Xamarin.Forms.Plugins#1]
Wondering if you tweeted this out for your entry into the contest? I couldn't find it. Let me know.

**Comment by paulpatarinski** [comment]
Hey James. I have not. I have been meaning to reach out to you to see if you can help me solve an issue before I tweet about it. For some reason I am getting an exception when using the plugin via nuget. But it works fine if I directly reference the assemblies.

**Comment by paulpatarinski** [comment]
More specifically when you launch the app the app flashes and then terminates. The output windows : 

01-04 11:45:04.618 D/Mono    ( 1329): Assembly Loader probing location: 'Svg.Forms.Plugin.Abstractions'.
01-04 11:45:04.618 F/monodroid-assembly( 1329): Could not load assembly 'Svg.Forms.Plugin.Abstractions' during startup registration.
01-04 11:45:04.618 F/monodroid-assembly( 1329): This might be due to an invalid debug instalation.
01-04 11:45:04.618 F/monodroid-assembly( 1329): A common cause is to 'adb install' the app directly instead of doing from the IDE.
The program 'Mono' has exited with code 0 (0x0).

**Comment by jamesmontemagno** [comment]
Have you full uninstalled and re-installed the test app from the Apps on in settings on the phone? 

I assume that it is in there and you are calling Init()?

When you install the NuGet have you made sure that everythign you are expecting is in the packages folder?

**Comment by paulpatarinski** [comment]
Is everything set to build in release?

> Checked the Config Manager all the projects are set to Release 

Have you full uninstalled and re-installed the test app from the Apps on in settings on the phone?

>  Tried a full uninstall/re-install did not help

I assume that it is in there and you are calling Init()?
> I am calling Init (Even though it does not seem to be required for Android). What is the point of calling Init again? 

When you install the NuGet have you made sure that everythign you are expecting is in the packages folder?
> Seems like all the files are there when I add the nuget package

If you clone the repo I have a sample app added that demonstrates the issue. 

https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SampleApp/PluginSampleApp/PluginSampleApp

I added an implementation for WinPhone and that seems to work fine, so the issue is only with Andoid

**Comment by jamesmontemagno** [comment]
I will try this in the morning to see what is going on... Odd.

James

On Sun, Jan 4, 2015 at 5:03 PM, Paul P <notifications@github.com> wrote:

> Is everything set to build in release?
>
> Checked the Config Manager all the projects are set to Release
>
> Have you full uninstalled and re-installed the test app from the Apps on
> in settings on the phone?
>
> Tried a full uninstall/re-install did not help
>
> I assume that it is in there and you are calling Init()?
>
> I am calling Init (Even though it does not seem to be required for
> Android). What is the point of calling Init again?
>
> When you install the NuGet have you made sure that everythign you are
> expecting is in the packages folder?
>
> Seems like all the files are there when I add the nuget package
>
> If you clone the repo I have a sample app added that demonstrates the
> issue.
>
>
> https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SampleApp/PluginSampleApp/PluginSampleApp
>
> I added an implementation for WinPhone and that seems to work fine, so the
> issue is only with Andoid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulpatarinski/Xamarin.Forms.Plugins/issues/1#issuecomment-68651475>
> .
>



-- 
James Montemagno
http://www.montemagno.com
@jamesmontemagno <http://www.twitter.com/jamesmontemagno>

**Comment by jamesmontemagno** [comment]
I figured it out...

So your DLLS are called SVG.*  however you are renaming them in your NuSpec to Svg.* 

Keep them all as SVG.* and it will work correclty.

**Comment by paulpatarinski** [comment]
That was it thanks a lot. It is all working now. Would you by any chance be interested in helping me with the iOS version? I don't have an iOS license or a Mac.
