### ISSUE TITLE
SvgImageRenderer multiple instances created for same svg

### ISSUE THREAD

**Issue by philipag** [paulpatarinski/Xamarin.Forms.Plugins#10]
Hi.

I declare an svgimage in XAML and use it as a static resource

<ContentPage.Resources
<ResourceDictionary
<abstractions:SvgImage BindingContext="{x:Reference mainPage}" x:Key="ArrowStraight" SvgAssembly="{Binding SvgAssembly}" SvgPath="TDSP.svg.bubble.svg" ...
....
<ContentView WidthRequest="30" Padding="0,0,0,0" Content="{StaticResource ArrowStraight}" ...

The problem is that each Content="{StaticResource ArrowStraight}"> reference causes the SVG file to be loaded because a new SvgImageRenderer is instantiated.  It is strange because only a single SvgImage instance is created.

Would there be a way for only a single renderer instance to be created for the same SvgImage instance?  I thought there was a 1-1 correspondence between XF control and renderer instances so I'm a bit confused...

Cheers
Philip

**Comment by paulpatarinski** [comment]
Hi Philip, 

I will try to take a look at this later today. I have never used the SvgImage as part of a ResourceDictionary, so I don't have any ideas off the top of my head.

Cheers
Paul

**Comment by philipag** [comment]
Hi Paul.
    
    Thanks for the quick reply.  I also posted at
    https://forums.xamarin.com/discussion/comment/105245#Comment_105245
    since this looks to be a Xamarin issue.  If you can post there as
    well with your findings this would be great.  If you can confirm
    what I found I can file a bug report.   If the Xamarin issue cannot
    be resolved perhaps a modification to your code which statically
    caches all loaded SVGs would make sense.  Perhaps just change
    Snippet
    _svgStreamByPath to be static?
    
    Cheers
    Philip
    
    Paul P wrote:
    
      Hi Philip, 
      I will try to take a look at this later today. I have never
        used the SvgImage as part of a ResourceDictionary, so I don't
        have any ideas off the top of my head.
      Cheers
        Paul
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by paulpatarinski** [comment]
Hey Philip, 

I had a chance to take a look at this. I don't think the problem is necessarily with an extra renderer being created (I tried making the collection static), but rather something with the Image implementation in Forms. No exceptions are thrown and the logic executes, but only a single image/svg will get rendered. I have created a page demonstrating the issue exists with Images as well : 

https://github.com/paulpatarinski/Xamarin.Forms.Plugins/blob/master/SVG/SampleApp/SampleApp/Pages/ViaResources.xaml

I will update the forums post as well as create a support ticket for Xamarin. 

On a different note I also improved the implementation a lot : 
  > It is now loading the svgs asynchronously 
 > I am now caching the streams in a static dictionary to increase performance
 > Some memory improvements

**Comment by paulpatarinski** [comment]
Bug Filed : https://bugzilla.xamarin.com/show_bug.cgi?id=27292

**Comment by philipag** [comment]
Nice work!
    
    Paul P wrote:
    
    
      Hey Philip, 
      I had a chance to take a look at this. I don't think the
        problem is necessarily with an extra renderer being created (I
        tried making the collection static), but rather something with
        the Image implementation in Forms. No exceptions are thrown and
        the logic executes, but only a single image/svg will get
        rendered. I have created a page demonstrating the issue exists
        with Images as well : 
      https://github.com/paulpatarinski/Xamarin.Forms.Plugins/blob/master/SVG/SampleApp/SampleApp/Pages/ViaResources.xaml
      I will update the forums post as well as create a support
        ticket for Xamarin. 
      On a different note I also improved the implementation a lot :
      
      
        It is now loading the svgs asynchronously 
          I am now caching the streams in a static dictionary to
          increase performance
          Some memory improvements
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by paulpatarinski** [comment]
I guess this is expected behavior. Here is the proposed approach by Xamarin :

 an Image is a VisualElement in Xamarin.Forms, just like Label, or Button, and
VisualElements can not be used multiple times simultaneously (re-using is
fine).
By declaring the Image as a resource, you are reusing the same Image instance
over and over again, and that's why only one is visible.

In your case, I'd define a Style for the Image in the ResourceDictionary, and
apply the same style to the multiple image instance,
